### ISSUE TITLE
Feature Request: Monster stats & Formulas

### ISSUE THREAD

**Issue by salvdev** [aEnigmatic/ffbe#1]
Not sure if it's possible, but if it is, any chance on getting monster stats?

Also, are the damage/healing formulas available? The ones on the wikis are just estimated formulas.

**Comment by aEnigmatic** [comment]
Monster stats are possible, but only on a one by one base, as they're sent by the server when you start a mission.

Exact damage formulas are not known yet, the closest I know of is from Ailandi Sensei on discord: 
`Damage = [Variance * (85%-100%) * Chain Modifier] * [1 + (Unit Level / 1)] * [(Unit ATK^2) / ((Enemy DEF * (1-Break)) * (1-Ignore Def))) * Killer Effects * Skill Modifier * Elemental Weakness]`

**Comment by aEnigmatic** [comment]
If you want the stats of particular monsters, tell me.  
You could also also hit me up on the ffbe discord, where I sometimes share stuff on monsters (e.g. bosses like Gilgamesh)

**Comment by salvdev** [comment]
Sounds great, thanks a lot of the data dump!
