### ISSUE TITLE
Question: How to associate an item / equipment / ability with how its obtained

### ISSUE THREAD

**Issue by bgarrison25** [aEnigmatic/ffbe#11]
So I am looking to add a filter to my program that allows you to filter out items based on how they are obtained (tmr / event / etc). Any idea how i might do that using this data? I can't seem to find an association of this type for the equipment

**Comment by bgarrison25** [comment]
I take that back...I can look at Unit TMR's to determine which equipment / materia's come from TMR's....any idea how to determine which come from an event or star quartz?

**Comment by aEnigmatic** [comment]
For star quartz you can take a look at mog_king i believe (which is a misnomer and should be called "medal exchange" or smth)  
There's nothing in the data that ties items to events, though.
