### ISSUE TITLE
Esper stats on global version

### ISSUE THREAD

**Issue by salvdev** [aEnigmatic/ffbe#12]
I just rebuilt the Esper Simulator on ffbedb using your data but I'm not sure if I got the right esper stats. One of my users just notified me that Siren's 3star max HP and Ifrit's 3star max HP don't match with his summon in the game nor the data on the english wiki. Are the base stats in the Entries array in Summons.json the proper stats?

**Comment by aEnigmatic** [comment]
Hey, the "problem" is that, technically, the 3* espers go up to max level 100, but in-game you can only level them to 60.  
Apparently, they said there might be other chances to upgrade them further with events or something.

**Comment by salvdev** [comment]
Alright, thanks for the explanation. I'll manually set the stats.
