### ISSUE TITLE
French translations gone from skills and limit burst files

### ISSUE THREAD

**Issue by Wisdomb33r** [aEnigmatic/ffbe#15]
Hi aEnigma,
I can see that you removed the strings from skills and limit bursts files. I'm using your data mining as a data source for my french website, and these are now missing for proper pages display.
It is possible to revert this change from your file structure ? Or maybe publish these in specific files ?

Would be awesome if you can (otherwise I'll find other solution, but have yet to figure out what).
Thanks in advance for your answer,

Best regards,
Wis

**Comment by aEnigmatic** [comment]
Hey, 
they are still available from the [strings repo](https://github.com/aEnigmatic/ffbe-gl-strings), which is updated at the same time as this one.

**Comment by Wisdomb33r** [comment]
Okaaay, did not note this repository (not highlighted in your personal profile, need to search specifically for it).
Fair enough, i'll update my scripts accordingly.
Cheers once more for your work !
