### ISSUE TITLE
Question about hits and frames parsing

### ISSUE THREAD

**Issue by Wisdomb33r** [aEnigmatic/ffbe#18]
Hi aEnigma,
I'm trying to figure out how to correctly parse the hits and frames of skills when it mixes damaging effects AND non-damaging ones.

I have three different cases to explain my trouble. First let's take Shine Surprise Attack +1 (702490), which have 3 effects, and only one table of hits/frames : 

- "attack_frames": [[12,  22]],

In this case, frames are available for damaging effects only (effect 1, which is physical damage).

Now let's consider Eleven's Gigagash (510751), which have 2 effects and two different table of hits/frames :

- "attack_frames": [[42,  48,  54,  60,  66,  72,  78,  84,  90], [42,  48,  54,  60,  66,  72,  78,  84,  90]],

Oddly in this case, it seems there is BS chain frames for the non-damaging effect 33 (imperil). BTW, one of the effect of the Shine example is also an imperil with ID 33.

Now another example with DKLeon's Dark Servant Blade (509923) :

- [[0], [0], [70,  76,  82,  88,  94,  100,  106], [112]],

There is frames for the non-damaging effects, but here with 0 value.
There must be an algorithm to correctly parse the frames of the damaging skill. However, I really cannot figure out what it is. In the Surprise Attack +1 case, the game must ignore there is two non-damaging effects to find the attack frames, while in the other cases similar effects do have frames.

Do you have any idea for an algorithm to achieve what I'm looking for ?

**Comment by lyrgard** [comment]
I'm interested by the answer too. I was supposing the the frames data was
only for damaging effects, until I saw those [0] frames ^_^

**Comment by aEnigmatic** [comment]
TBH, I don't really know, the game will probably either use a previous value or a default value...

**Comment by Wisdomb33r** [comment]
I'll try to test if there is the same number of frames tables than effects in the skill.
If yes, I'll use the frames tables located at the index of the effects.
If no, I'll use the frames at the beginning of the table, assuming all the frames are for the damages.

This would be okay for these three specific skills. Need to implement this and test it a bit with more skills.

@lyrgard Read on reddit your health is good again, good news ! I'll try to implement quickly my idea to extract the frames of the damaging effects. I'll come back to you with the results. Btw, I'm currently implementing a parser to transform aEnigma data dump into **french** readable text. If one day my code does interest you for any reason, let me know.

**Comment by Wisdomb33r** [comment]
It is indeed working for the three skills I took as examples. But I quickly found one which is NOT working : Saber of Adversity (509912) from Wild Rose Firion...

There is 5 effects :

```
        "effects": [
            "No effect",
            "Increase physical damage against [...] for 3 turns",
            "Physical damage (2x, ATK) to one enemy",
            "Physical damage (10.8x, ATK) to one enemy",
            "Gain 3 uses [...] for 2 turns"
        ],
```

And the frames are :

"attack_frames": [[0], [0], [110,  120,  130,  140,  150,  160,  170,  180,  190], [200]],

Only 4 tables, not 5. I could refine my algorithm to exclude the effects which are parsed to "No effect", but this is getting really clumsy...

**Comment by Wisdomb33r** [comment]
And here I have it, Serena's Deliverance (233160) :

```
        "effects": [
            "No effect",
            "Increase magic damage against Reapers by 50% to caster for 2 turns",
            "Magic* damage (4.5x, SPR) to one enemy"
        ],
```

And the frames :

`"attack_frames": [[50], [12], [12]],`

Unline Firion's case, the "No effect" have frames attached to it. The "No effect" has the exact same configuration (effect ID 24, 6 zeros as parameters) for both Firion's and Serena's cases.

Feel free to share if you have any idea, I must face it, I do not understand -_-

**Comment by ygalland** [comment]
Hi guys,

Unfortunately there is no real logic way to get the attack_frames...
I parse those data since 2 years and I always need to made some adjustments because the same effect isn't showing the same result for the frames...
Sometime it's a 0, sometimes it doesn't show and even worse sometime it has a real value...

I already try lot of things to improve the way to get the frames but never find the perfect solution because the data implemented in FFBE are a real mess...

I think the only to understand how they manage to use those data in game it's to reverse engineering the code itself...

But if you manage to find a way to get the good values in any cases I'm interested :)

Bismark

**Comment by lyrgard** [comment]
I propose to try to make some rules, and see if we find cases that doesn't match.

What about :

```
nbDamageEffect = count of effects that do damage
if (attack_frames.lenght == nbDamageEffect) {
    Assign each frame to a damage effect, in same order
} else {
    Assign each frame to each effect, in same order, until no more frame.
}
```

Is there skills that don't match that ? If I didn't checked wrong, it should work for all examples above

**Comment by Wisdomb33r** [comment]
@lyrgard I'm currently testing a slightly different version of your algorithm, but which might have the exact same result (except for a small detail you did not include) :

```
frames = empty table
lastIndexOfDamageEffect = find the last index of effect that do damage, but is not DOT (!= 139)
if(attack_frames.length > lastIndexOfDamageEffect) {
  for all effects {
    if(effect do damage but is not DOT) {
      concat to frames local variable the frames corresponding to the effect index
    }
  }
} else {
  assign each frame to a damage effect, in same order
}
```

My else case correspond to your if case exactly. But in your else case (= my if case), you do have the risk of adding "0 0 ..." in front of Firion's frames. You need afterwards to exclude the frames you assigned to non-damaging effects. That why I have an inner if test.

Up to now, I did not find any case which is not correct under this algorithm. But I suspect there might be problems with delayed attacks and/or jumps. DOT's seems to always be after the immediate damages, so excluding effect 139 seems to do the trick.

**Comment by lyrgard** [comment]
I don't understand why you say I would add "0 0" in front of firion's frames. 

To be more clear, in my else, I said "Assign each frame to each effect, in same order, until no more frame.", but in reality, I just drop frame information for not damaging skills. It was just to explain how the attack frames are matched to the attack effects.

Jump and DOT probably can't have frames, so just treat them as non damaging effect for that algorithm (and that's why it's so hard for them to fix Reberta, the idea is to do a chaining jump, but I think the code doesn't allow jump to have frames in FFBE).

Delayed attacks can have frames, but it should have its own frames in the attack_frames. Just consider them as if they were on a separate skill, for chaining purpose.

**Comment by Wisdomb33r** [comment]
@lyrgard Ho, okay, then what you do is similar to what I do. I'm stacking the damaging frames into a local variable, and you are assigning the frames to the damaging effects (based on index), then construct the frames based on damaging effects only. That should output the exact same result.

If you find any skill which is not working properly, please let me know.

**Comment by Wisdomb33r** [comment]
Closing this ticket as it seems the discussions on this topic will not continue further. Cheers all !

@ygalland It seems my algorithm is working. I could not find any skill which frames are not correctly parsed with it.

**Comment by lyrgard** [comment]
Ok, I think I found how it works, I found an algorithm that works for all cases, and is logical enough.

You take the attack_frames array, and if there are more effects that attack frames, you increase it's size by repeating the last value. Then you have the attack frames for each effect. And obviously, all not attack/heal and so on effects will just ignore it

**Comment by lyrgard** [comment]
I'll use a function like that to retrieve the data now :

```
function getValueAtIndex(array, index) {
    if (!Array.isArray(array)) {
        array = [array];
    }
    if (index < array.length) {
        return array[index];
    } else {
        return array[array.length - 1];
    }
}
```
