### ISSUE TITLE
Short descriptions null in materia file

### ISSUE THREAD

**Issue by Wisdomb33r** [aEnigmatic/ffbe#19]
Hi aEnigma,
I just saw that your latest DM version has `"desc_short": [null, null, null, null, null, null],` for ALL materia of the game.
Because the desc_short field is still present (but with null values), this looks like a regression. Or did you remove them because they are always the same as desc_long value ? 
Thank you in advance for your help and cheers !

**Comment by ygalland** [comment]
It should be in the strings repo https://github.com/aEnigmatic/ffbe-gl-strings
In the MST_ABILITY_SHORTDESCRIPTION.json file

**Comment by aEnigmatic** [comment]
Fixed, thanks for reporting :)
