### ISSUE TITLE
Some desc_short of materias still missing

### ISSUE THREAD

**Issue by Wisdomb33r** [aEnigmatic/ffbe#20]
Hi aEnigma,
Your last DM version holds most of the desc_short fields for materias, but there are still some missing.
The Astrals' Protection (504231800), Mark of the Glacian (504231812) are among them. Only a very few are still missing (at least among those having translations in all languages).
Can you have a look at them ?

**Comment by aEnigmatic** [comment]
Both entries (`MST_MATERIA_SHORTDESCRIPTION_504231800` `MST_MATERIA_SHORTDESCRIPTION_504231812`) are simply missing from the `F_TEXT_MATERIA_SHORTDESCRIPTION` localization table.

**Comment by Wisdomb33r** [comment]
All right, guess I'll update my code to fallback to the long description if short is missing. Thank you for the check.
