### ISSUE TITLE
How to file

### ISSUE THREAD

**Issue by bolbovic** [aEnigmatic/ffbe#3]
Hi!
Thanks for the really good work!
I'd like to do the same for JP, is there a way you could update the readme or create a how to another file to explain how you do it? Where are the informations in the apk or in the downloaded files, which tools you use, etc?
Thanks!

**Comment by aEnigmatic** [comment]
Hey, the game files are encrypted which means you can't read any real data without the encryption keys, which I won't share, as they open the door to cheating, sorry.

I'll probably add JP data sooner or later, it just hasn't been a priority yet.

**Comment by bolbovic** [comment]
I can understand for the encryption keys.
But is there a reason you don't share the files directly but only the modified files you are making?
I mean, the data you give is not the unencrypted raw file data, right? You are running probably a script to generate those json files. Would you mind sharing it?
There is some data missing in your files so sometimes it's not usable and that's a shame! Thanks.

**Comment by aEnigmatic** [comment]
You can use https://github.com/Mila432/ffbe_files for the raw game files
