### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by jhoalx** [aEnigmatic/ffbe#5]
Hi, i could not find you on reddit, so i came here as my last option

wanted to contact you to see what you think about this
https://github.com/jhoalx/ffbeSchemas

i'm starting a hobby learning project and will be using your repo a lot, i thought you might wanted to check it

**Comment by aEnigmatic** [comment]
Hey, my reddit username is /u/__solaris__, and I'm also on the /r/ffbe discord.  
I haven't created a scheme etc. because for some things the structure might still change, though it got rather stable overall.

**Comment by jhoalx** [comment]
ill try to keep em updated, is a WIP tho.
