### ISSUE TITLE
Something weird about Trance Terra's Dual White Magic (219500)

### ISSUE THREAD

**Issue by AaronShockley** [aEnigmatic/ffbe#6]
Its effects (and effects_raw) look like a damaging ability for some reason.

"Magic light damage (8.67x, MAG) to all enemies (ignore cover and reflect)"
[[2, 1, 70, [0, 0, 650, 25]]

This is the only "70" skill (magic damage skill) with attack_count: [[0]].

Is there a chance you're pulling the wrong data for the skill?

**Comment by aEnigmatic** [comment]
As far as I can tell, 219500 is only a dummy entry for the 2nd effect of Magical Activation+2 (704470)
Possibly for the ability icon.
