### ISSUE TITLE
AI files??

### ISSUE THREAD

**Issue by pureswing** [aEnigmatic/ffbe#8]
greeting! I love your work and contribution to ffbe community ;) ...just wondering if you have plan to create any type of files with the AI (Monsters) skills ?? If not can you give me a hand finding and reading (text) those files or if there another project with this info??

Thanks and keep your hard work 👍

**Comment by aEnigmatic** [comment]
The problem with AI is that you also need the corresponding MonsterSkillsetID to get a usable result.   
The AI basically says to skill #x from the skillset under conditions y,z etc.

Sometimes the skillset id is the same as the ai id, or if it's a new AI one can infer from recent changes which skillset belongs to it, but its not possible to just parse all AIs and get usable results.

I usually release the AIs for trials and events for the wiki in the discord channel (a small number is also listed under https://exvius.gamepedia.com/AI), so if you're interested you could just lurk there ;)

**Comment by pureswing** [comment]
@zippeurfou what you mean with all the link are dead?, I just checked the wiki and everything looks fine, using chrome. https://exvius.gamepedia.com/Chamber_of_the_Fallen

**Comment by pureswing** [comment]
Okay, well I don't see nothing wrong. A fragment from your links:
```
##
# Mission 'Conqueror of Izander - ELT' (9002604)
##

##
# Monster Info
##
#
# Monster  Tolfidan (900010398)
# Race     Dragon
# Level    99
# Actions  5-5
#
#
# Stats
#        HP          4000000
#        MP            10000
#        ATK             240
#        DEF              70
#        MAG             210
#        SPR              70
#
#
# Damage resist
#        physical          0%
#        magical           0%
#
#
# Element resist
#        Fire             50%
#        Ice               0%
#        Lightning         0%
#        Water             0%
#        Wind              0%
#        Earth             0%
#        Light             0%
#        Dark             50%
```

**Comment by aEnigmatic** [comment]
@zippeurfou Yeah, that AI list is pretty incomplete.  
I might add them to a different repo, for now I've added that AI to a [gist](https://gist.github.com/aEnigmatic/0f4f32f6afbc39ec5a370fa87e946784)

**Comment by pureswing** [comment]
@aEnigmatic Hi!, I know this is not related to FFBE but I wonder if you have any Idea on how to datamining Dissidia Opera Omnia. I can't find any information about that and in the subreddit they are exceptical to talk about that.  :(

**Comment by aEnigmatic** [comment]
Haven't looked at the game files at all, so no idea

**Comment by aEnigmatic** [comment]
For recent events, take a look at https://gist.github.com/aEnigmatic.
